name: user_management
description: A new Flutter project for assessment.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_secure_storage: ^8.0.0
  image_picker: ^0.8.7
  http: ^0.13.5
  hive_flutter: ^1.1.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/user_login.png
    - assets/images/signup.png
